object AppConfig {
    const val applicationId = "com.naturaz.bd"
    const val compileSdk = 34
    const val minSdk = 24
    const val targetSdk = 34
    const val versionCode = 1
    const val versionName = "1.0.0"
}

object Versions {
    const val gradle = "8.2.2"
    const val kotlin = "1.9.10"
    const val composeBom = "2023.10.01"
    const val composeCompiler = "1.5.3"
    const val coreKtx = "1.12.0"
    const val lifecycle = "2.6.2"
    const val activityCompose = "1.8.2"
    const val navigation = "2.7.6"
    const val hilt = "2.48"
    const val hiltNavigation = "1.1.0"
    const val coroutines = "1.7.3"
    const val retrofit = "2.9.0"
    const val okHttp = "4.11.0"
    const val serialization = "1.6.1"
    const val room = "2.6.1"
    const val dataStore = "1.1.0-alpha06"
    const val coil = "2.5.0"
    const val accompanist = "0.33.2-alpha"
    const val firebaseBom = "32.7.2"
    const val maps = "18.2.0"
    const val location = "21.0.1"
    const val cameraX = "1.3.0"
    const val workManager = "2.9.0"
    const val timber = "5.0.1"
    const val leakCanary = "2.12"
    const val chucker = "4.0.0"
    const val biometric = "1.2.0-alpha05"
    const val securityCrypto = "1.1.0-alpha06"
    const val espresso = "3.5.1"
    const val junit = "4.13.2"
    const val junit5 = "5.10.1"
    const val junit5Android = "1.3.0"
    const val mockk = "1.13.8"
    const val turbine = "1.0.0"
    const val composeUiTestJunit4 = "1.5.4"
    const val paging = "3.2.1"
    const val protobuf = "3.25.1"
    const val protobufPlugin = "0.9.4"
    const val roomPaging = "2.6.1"
    const val serializationConverter = "1.0.0"
    const val firebaseUiAuth = "8.0.2"
    const val playServicesAuth = "20.7.0"
    const val composeMaterial3Windows = "1.1.2"
    const val ossLicenses = "17.0.1"
    const val ksp = "1.9.10-1.0.13"
}

object BuildPlugins {
    const val androidApplication = "com.android.application"
    const val kotlinAndroid = "org.jetbrains.kotlin.android"
    const val hilt = "com.google.dagger.hilt.android"
    const val ksp = "com.google.devtools.ksp"
    const val kotlinParcelize = "kotlin-parcelize"
    const val kotlinSerialization = "org.jetbrains.kotlin.plugin.serialization"
    const val googleServices = "com.google.gms.google-services"
    const val crashlytics = "com.google.firebase.crashlytics"
    const val secrets = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin"
}

object Libs {
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycle}"
    const val lifecycleRuntimeCompose = "androidx.lifecycle:lifecycle-runtime-compose:${Versions.lifecycle}"
    const val lifecycleViewModel = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycle}"
    const val lifecycleViewModelCompose = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.lifecycle}"
    const val activityCompose = "androidx.activity:activity-compose:${Versions.activityCompose}"
    const val navigationCompose = "androidx.navigation:navigation-compose:${Versions.navigation}"
    const val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:${Versions.navigation}"
    const val composeBom = "androidx.compose:compose-bom:${Versions.composeBom}"
    const val composeUi = "androidx.compose.ui:ui"
    const val composeUiGraphics = "androidx.compose.ui:ui-graphics"
    const val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview"
    const val composeMaterial3 = "androidx.compose.material3:material3"
    const val composeMaterialIcons = "androidx.compose.material:material-icons-extended"
    const val composeConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:1.0.1"
    const val composeWindowSize = "androidx.compose.material3:material3-window-size-class"
    const val accompanistSystemUi = "com.google.accompanist:accompanist-systemuicontroller:${Versions.accompanist}"
    const val accompanistPermissions = "com.google.accompanist:accompanist-permissions:${Versions.accompanist}"
    const val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val coroutinesPlayServices = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:${Versions.coroutines}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofitSerialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${Versions.serializationConverter}"
    const val okHttp = "com.squareup.okhttp3:okhttp:${Versions.okHttp}"
    const val okHttpLogging = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    const val serializationJson = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.serialization}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hilt}"
    const val hiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:${Versions.hiltNavigation}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.room}"
    const val roomKtx = "androidx.room:room-ktx:${Versions.room}"
    const val roomPaging = "androidx.room:room-paging:${Versions.roomPaging}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val dataStorePreferences = "androidx.datastore:datastore-preferences:${Versions.dataStore}"
    const val dataStoreProto = "androidx.datastore:datastore:${Versions.dataStore}"
    const val protobufLite = "com.google.protobuf:protobuf-javalite:${Versions.protobuf}"
    const val coilCompose = "io.coil-kt:coil-compose:${Versions.coil}"
    const val coilGif = "io.coil-kt:coil-gif:${Versions.coil}"
    const val firebaseBom = "com.google.firebase:firebase-bom:${Versions.firebaseBom}"
    const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
    const val firebaseCrashlytics = "com.google.firebase:firebase-crashlytics-ktx"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging-ktx"
    const val firebasePerformance = "com.google.firebase:firebase-perf-ktx"
    const val firebaseConfig = "com.google.firebase:firebase-config-ktx"
    const val firebaseAuth = "com.google.firebase:firebase-auth-ktx"
    const val firebaseUiAuth = "com.firebaseui:firebase-ui-auth:${Versions.firebaseUiAuth}"
    const val playServicesAuth = "com.google.android.gms:play-services-auth:${Versions.playServicesAuth}"
    const val maps = "com.google.android.gms:play-services-maps:${Versions.maps}"
    const val location = "com.google.android.gms:play-services-location:${Versions.location}"
    const val cameraXCore = "androidx.camera:camera-core:${Versions.cameraX}"
    const val cameraXCamera2 = "androidx.camera:camera-camera2:${Versions.cameraX}"
    const val cameraXLifecycle = "androidx.camera:camera-lifecycle:${Versions.cameraX}"
    const val cameraXVideo = "androidx.camera:camera-video:${Versions.cameraX}"
    const val cameraXView = "androidx.camera:camera-view:${Versions.cameraX}"
    const val cameraXExtensions = "androidx.camera:camera-extensions:${Versions.cameraX}"
    const val workRuntime = "androidx.work:work-runtime-ktx:${Versions.workManager}"
    const val pagingRuntime = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val pagingCompose = "androidx.paging:paging-compose:${Versions.paging}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val leakCanary = "com.squareup.leakcanary:leakcanary-android:${Versions.leakCanary}"
    const val chucker = "com.github.chuckerteam.chucker:library:${Versions.chucker}"
    const val chuckerNoOp = "com.github.chuckerteam.chucker:library-no-op:${Versions.chucker}"
    const val biometric = "androidx.biometric:biometric:${Versions.biometric}"
    const val securityCrypto = "androidx.security:security-crypto:${Versions.securityCrypto}"
    const val ossLicenses = "com.google.android.gms:play-services-oss-licenses:${Versions.ossLicenses}"
}

object TestLibs {
    const val junit = "junit:junit:${Versions.junit}"
    const val junit5Api = "org.junit.jupiter:junit-jupiter-api:${Versions.junit5}"
    const val junit5Params = "org.junit.jupiter:junit-jupiter-params:${Versions.junit5}"
    const val junit5Engine = "org.junit.jupiter:junit-jupiter-engine:${Versions.junit5}"
    const val mockk = "io.mockk:mockk:${Versions.mockk}"
    const val turbine = "app.cash.turbine:turbine:${Versions.turbine}"
    const val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.coroutines}"
    const val androidJUnitExt = "androidx.test.ext:junit:1.1.5"
    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espresso}"
    const val composeUiTestJunit4 = "androidx.compose.ui:ui-test-junit4:${Versions.composeUiTestJunit4}"
    const val composeUiTestManifest = "androidx.compose.ui:ui-test-manifest"
    const val hiltTesting = "com.google.dagger:hilt-android-testing:${Versions.hilt}"
    const val junit5AndroidRunner = "de.mannodermaus.junit5:android-test-runner:${Versions.junit5Android}"
    const val junit5AndroidCore = "de.mannodermaus.junit5:android-test-core:${Versions.junit5Android}"
}

object DebugLibs {
    const val composeUiTooling = "androidx.compose.ui:ui-tooling"
    const val composeUiTestManifest = TestLibs.composeUiTestManifest
}
